const std = @import( "std"  );
const def = @import( "defs" );

const gbl = @import( "../gameGlobals.zig" );
const gdf = @import( "../gameDefs.zig"    );

const ResType = @import( "resourceData.zig"       ).ResType;
const InfType = @import( "infrastructureData.zig" ).InfType;


pub const PopType = enum( u8 )
{
  pub const count = @typeInfo( @This() ).@"enum".fields.len;

  pub inline fn toIdx( self : @This() ) usize { return @intFromEnum( self ); }
  pub inline fn fromIdx( i : usize ) @This()  { return @enumFromInt( i ); }

  HUMAN,

  // TODO : add other pop types here eventually

  pub inline fn getInfStore( self : PopType ) InfType // TODO : move to data array ?
  {
    return switch( self )
    {
      .HUMAN => .HOUSING,  // TODO : update once multiple pop types exist
    //else   => .HOUSING,
    };
  }


  pub fn getMetric_f32( self : PopType, metric : PopMetricEnum ) f32
  {
    return @floatCast( popMetricData.get( self, metric ));
  }
  pub fn getMetric_f64( self : PopType, metric : PopMetricEnum ) f64
  {
    return popMetricData.get( self, metric );
  }
  pub fn getMetric_u32( self : PopType, metric : PopMetricEnum ) u32
  {
    return @intFromFloat( popMetricData.get( self, metric ));
  }
  pub fn getMetric_u64( self : PopType, metric : PopMetricEnum ) u64
  {
    return @intFromFloat( popMetricData.get( self, metric ));
  }

  pub fn getResMetric_f32( self : PopType, metric : PopResMetricEnum, resT : ResType ) f32
  {
    return @floatCast( popResMetricTable.get( self, metric, resT ));
  }
  pub fn getResMetric_f64( self : PopType, metric : PopResMetricEnum, resT : ResType ) f64
  {
    return popResMetricTable.get( self, metric, resT );
  }
  pub fn getResMetric_u32( self : PopType, metric : PopResMetricEnum, resT : ResType ) u32
  {
    return @intFromFloat( popResMetricTable.get( self, metric, resT ));
  }
  pub fn getResMetric_u64( self : PopType, metric : PopResMetricEnum, resT : ResType ) u64
  {
    return @intFromFloat( popResMetricTable.get( self, metric, resT ));
  }
};


// ================================ POPULATION BASE METRICS GRID ================================
// NOTE : Mostly-static per-population values

pub var popMetricData : def.GenDataGrid( f64, PopType, PopMetricEnum ) = .{};

pub const PopMetricEnum = enum( u8 )
{
  pub const count = @typeInfo( @This() ).@"enum".fields.len;

  MASS,
  HSNG_COST, // Base housing cost in units of "housing" ( generated by HOUSING )
  POLLUTION,
  NATALITY,  // Base natality rate per week ( modified by resT/job access )
  FATALITY,  // Base fatality rate per week ( natural causes, always applied )
};


// ================================ POPULATION RES METRICS GRID ================================
// NOTE : Mostly-static per-population & resource values

pub var popResMetricTable : def.GenDataCube( f64, PopType, PopResMetricEnum, ResType ) = .{};

pub const PopResMetricEnum = enum( u8 )
{
  pub const count = @typeInfo( @This() ).@"enum".fields.len;

  CONS, // Base res consumption per pop
  PROD, // Base res produciton  per pop ( * FLM_LVL )

  MORT, // Additional mortality rate per week at ZERO access to the specified resource
};


// ================================ POPULATION STATE GRID ================================
// NOTE : used in Economy to store local mutable values

pub const PopStateData = def.GenDataGrid( f64, PopStateEnum, PopType );

pub const PopStateEnum = enum( u8 )
{
  pub const count = @typeInfo( @This() ).@"enum".fields.len;

  COUNT,    // Current population count
  LIMIT,    // Current housing capacity

  STARVE,   // Amount lost from unatural deaths last tick
  DEATH,    // Amount lost from all deaths last tick
  BIRTH,    // Amount gained from births last tick

  // TODO : Hook in the monetary values bellow properly
  EXPENSE,  // Amount of money spent to fulfill their needs
  REVENUE,  // Amount of money gained by via WORK production
  SAVINGS,  // Stored profits from previous ticks ( decays via inflation )

  FLM_LVL,  // How fulfilled their needs ended up being last tick
};


// ================================ DATA INITIALIZATION ================================

pub fn loadPopulationData() void
{
  popMetricData.fillWith(     0.0 );
  popResMetricTable.fillWith( 0.0 );


  // ================================ BASE METRICS ================================

  popMetricData.set( .HUMAN, .MASS,      0.0600 ); // In tons ( 60 Kgs )
  popMetricData.set( .HUMAN, .HSNG_COST, 1.0000 ); // Housing "space" neede for each pop
  popMetricData.set( .HUMAN, .POLLUTION, 0.0500 ); // ~2.6 tCO2e/yr - first-world all-electric
  popMetricData.set( .HUMAN, .NATALITY,  0.0003 ); // ~1.6% annual — colony growth rate
  popMetricData.set( .HUMAN, .FATALITY,  0.0001 ); // ~0.5% annual — advanced medicine, ~200yr life expectancy



  // ================================ RESOURCE METRICS ================================
  // NOTE : Per week. Units in gameDefs.zig

  popResMetricTable.set( .HUMAN, .PROD, .WORK,  0.350 ); // 0.45 prod - 0.10 cons
//popResMetricTable.set( .HUMAN, .CONS, .WORK,  0.450 ); // Average workweek
//popResMetricTable.set( .HUMAN, .CONS, .WORK,  0.200 ); // Services consumption

//popResMetricTable.set( .HUMAN, .CONS, .FUEL,  0.000 ); // All transport is electric
  popResMetricTable.set( .HUMAN, .CONS, .FOOD,  0.015 );
  popResMetricTable.set( .HUMAN, .CONS, .WATER, 0.500 );
  popResMetricTable.set( .HUMAN, .CONS, .POWER, 0.500 ); // 0.4 base + 0.1 for electric transport
  popResMetricTable.set( .HUMAN, .CONS, .PART,  0.003 );

  // Mortality rates at ZERO access (per week)
  // Scaled by (1 - access)^exponent for partial shortages
  popResMetricTable.set( .HUMAN, .MORT, .WATER, 0.0200 ); // Dehydration — lethal in days, mass death in 1-2 weeks
  popResMetricTable.set( .HUMAN, .MORT, .FOOD,  0.0100 ); // Starvation  — serious in 3 weeks, mass death in 4-8 weeks
  popResMetricTable.set( .HUMAN, .MORT, .POWER, 0.0005 ); // Exposure    — environment dependent, slow killer
}


